version: 2.1
jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - run: circleci orb validate orb.yml
workflows:
  version: 2.1
  validate:
    jobs:
      - validate