version: 2.1
jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    steps:
      - run : echo "hello"
      - run: circleci orb validate orb.yml
# workflows:
#   version: 2
#   joke:
#     jobs:
#       - validate